name: Test Pull Request

on:
  pull_request:
    branches:
    - main

jobs:
  test-pull-request:
    name: Test Pull Request
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Build
      run: |
        ./scripts/build.sh
